Repository RajatShenoi/SocialNetwork, pull requests merged in 2023-09, with the labels that each got.

#7 Created CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#8 Create README.md
  README.md
Labels: documentation, enhancement, good first issue

#13 Created SECURITY.md
  SECURITY.md
Labels: documentation, security

#14 Modified README.md
  README.md
Labels: documentation
